version: "3.7"

services:
  service-a:
    build:
      context: ./../../
      dockerfile: ./scripts/docker/service-a.dockerfile
    command: "sh /srv/service/entrypoint.sh"
    volumes:
      - ./../../packages/service-a:/srv/service
  service-b:
    build:
      context: ./../../
      dockerfile: ./scripts/docker/service-b.dockerfile
    command: "sh /srv/service/entrypoint.sh"
    volumes:
      - ./../../packages/service-b:/srv/service

  db:
    image: postgres:12.0-alpine

  adminer:
    image: adminer
    ports:
      - 8080:8080
